lib/grps_web/router.ex
defmodule GrpsWeb.Router do
  use GrpsWeb, :router
  import GrpsWeb.Plugs.UserAuth

  @moduledoc "The Web Application routes are defined here."

  @doc "This pipeline contains the plugs used during a regular HTTP call"
  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GrpsWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  @doc "This pipeline contains the plugs used during a JSON Api call"
  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GrpsWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/login", SessionController, :new
    post "/login", SessionController, :create
  end

  scope "/", GrpsWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/", PageController, :index
    delete "/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", GrpsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).

  # TODO: enable in Production but lock it down to only Forever Admins
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GrpsWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/grps_web/views/layout_view.ex
defmodule GrpsWeb.LayoutView do
  use GrpsWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/grps_web/templates/layout/main_nav.html.heex
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top" id="main-nav">
  <div class="container-fluid">
    <a href="/" class="navbar-brand">
      <%= img_tag(Routes.static_url(@conn, "/images/forever-logo-white.png"), style: "max-height: 25px") %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%= if @current_user do %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a href="#" class="nav-link active">My Groups</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link active">Group Memberships</a>
          </li>
        </ul>
        <%= if @current_user.role == "admin" do %>
          <ul class="navbar-nav me-2">
            <li class="nav-item">
              <a href="/dashboard" class="nav-link" method="get" target="_blank" rel="noopener noreferrer">Dashboard</a>
            </li>
          </ul>
        <% end %>
        <div class="text-light">
          <%= @current_user.name %>
          <%= if @current_user.avatar_url do %>
          <span><img src={@current_user.avatar_url} style="width: 24px; height: 24px" %></span>
          <% end %>
        </div>
        <%= link "Log out", to: Routes.session_path(@conn, :delete), class: "btn btn-sm btn-outline-secondary ms-2", method: :delete %>
      </div>
    <% else %>
      <%= link("Log In", to: "/login", class: "btn btn-sm btn-outline-secondary ms-2") %>
    <% end %>
  </div>
</nav>

lib/grps_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Forever Groups", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
  <%= render "main_nav.html", conn: @conn, current_user: @current_user %>

  <%= @inner_content %>
  </body>
</html>